apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-generator-prod-cision
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                dev: "true"
            values: 
              revision: HEAD # Have to configure branch for prod cluster
              env: dev
        - git:
            repoURL: https://github.com/araza-sre/argo-example
            revision: HEAD
            directories:
            - path: qa-everest-eks/*
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
      namespace: cision-devops
    spec:
      project: cision-devops
      source:
        repoURL: https://github.com/syed-zizou/org-two
        targetRevision: '{{values.revision}}'
        path: '{{path.basename}}/{{values.env}}'
      destination:
        server: '{{server}}'
        namespace: cision-devops
      syncPolicy:
        automated: 
          prune: true
  syncPolicy:
    # Don't delete Application's child resources, on parent deletion:
    preserveResourcesOnDeletion: false
